import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <section className='gradient-bg h-screen '>
        <div className='backdrop-blur-[10px] backdrop-saturate-[1.42] bg-[#11192863] h-screen'>
          <Navbar/>
          <Hero/>
        </div>
      </section>

    </>
  )
}
